/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugIndexRouteImport } from './routes/$slug/index'
import { Route as SlugTimerRouteImport } from './routes/$slug/timer'
import { Route as SlugSuccessRouteImport } from './routes/$slug/success'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugIndexRoute = SlugIndexRouteImport.update({
  id: '/$slug/',
  path: '/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugTimerRoute = SlugTimerRouteImport.update({
  id: '/$slug/timer',
  path: '/$slug/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugSuccessRoute = SlugSuccessRouteImport.update({
  id: '/$slug/success',
  path: '/$slug/success',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug/success': typeof SlugSuccessRoute
  '/$slug/timer': typeof SlugTimerRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug/success': typeof SlugSuccessRoute
  '/$slug/timer': typeof SlugTimerRoute
  '/$slug': typeof SlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug/success': typeof SlugSuccessRoute
  '/$slug/timer': typeof SlugTimerRoute
  '/$slug/': typeof SlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$slug/success' | '/$slug/timer' | '/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$slug/success' | '/$slug/timer' | '/$slug'
  id: '__root__' | '/' | '/$slug/success' | '/$slug/timer' | '/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugSuccessRoute: typeof SlugSuccessRoute
  SlugTimerRoute: typeof SlugTimerRoute
  SlugIndexRoute: typeof SlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/': {
      id: '/$slug/'
      path: '/$slug'
      fullPath: '/$slug/'
      preLoaderRoute: typeof SlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/timer': {
      id: '/$slug/timer'
      path: '/$slug/timer'
      fullPath: '/$slug/timer'
      preLoaderRoute: typeof SlugTimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug/success': {
      id: '/$slug/success'
      path: '/$slug/success'
      fullPath: '/$slug/success'
      preLoaderRoute: typeof SlugSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugSuccessRoute: SlugSuccessRoute,
  SlugTimerRoute: SlugTimerRoute,
  SlugIndexRoute: SlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
